import {createHmac} from 'node:crypto';
import {admin,config,db,json,sameOrigin,seed,validateWebhook} from './server';
import type {Product} from './catalog';
export async function GET(r:Request){try{const u=new URL(r.url);if(u.searchParams.get('admin')){admin(r);await seed();return json({webhook:(await db().prepare("SELECT value FROM settings WHERE key='webhook_url'").first<{value:string}>())?.value||'',configured:!!((await db().prepare("SELECT value FROM settings WHERE key='webhook_url'").first<{value:string}>())?.value||config().WEBHOOK_TEST_URL),products:(await db().prepare('SELECT * FROM products').all()).results,orders:(await db().prepare('SELECT * FROM orders ORDER BY created DESC LIMIT 100').all()).results,events:(await db().prepare('SELECT * FROM webhook_events ORDER BY created DESC LIMIT 50').all()).results});}if(u.searchParams.get('id')){const order=await db().prepare('SELECT id,username,items,total,method,status,wallet,payment,created,note FROM orders WHERE id=? AND token=?').bind(u.searchParams.get('id'),u.searchParams.get('token')||'').first();return order?json({order}):json({error:'Order not found. Check your order ID and tracking key.'},404);}await seed();return json({products:(await db().prepare('SELECT * FROM products WHERE active=1').all()).results,webhook:!!config().WEBHOOK_TEST_URL,card:false,crypto:false});}catch(e){console.error(e);return json({error:'Shop temporarily unavailable. Please try again.'},503);}}
export async function POST(r:Request){try{sameOrigin(r);const b=await r.json() as any;
if(b.action==='settings'){admin(r);const url=validateWebhook(String(b.url||''));await db().prepare("INSERT INTO settings (key,value) VALUES ('webhook_url',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(url).run();return json({ok:true});}
if(b.action==='product'){admin(r);const p=b.product as Product;if(!/^[a-z0-9-]{1,60}$/.test(p.id)||!p.name||p.name.length>100||!['Murder Mystery 2','Adopt Me!','Blox Fruits'].includes(p.game)||!Number.isInteger(p.price)||p.price<50||p.price>100000||!Number.isInteger(p.stock)||p.stock<0||p.stock>10000)return json({error:'Check product details, price and inventory.'},400);await db().prepare('UPDATE products SET name=?,price=?,stock=? WHERE id=?').bind(p.name,p.price,p.stock,p.id).run();return json({ok:true});}
if(b.action==='fulfill'){admin(r);if(!['test_ready','test_delivered'].includes(b.status))return json({error:'Invalid test status'},400);const result=await db().prepare("UPDATE orders SET status=?,note=? WHERE id=? AND status IN ('test_approved','test_ready')").bind(b.status,String(b.note||'').slice(0,1000),b.id).run();return result.meta.changes?json({ok:true}):json({error:'Only approved test orders can advance.'},400);}
if(b.action!=='checkout')return json({error:'Unknown action'},400);
if(!Array.isArray(b.items)||!b.items.length||b.items.length>20||!['demo','testcard'].includes(b.method)||!/^\w{3,20}$/.test(b.username||'')||!/^\S+@\S+\.\S+$/.test(b.email||'')||b.email.length>254)return json({error:'Enter a valid test username, email and cart.'},400);
// This sandbox can never process arbitrary card data. Only these public synthetic fixtures are accepted.
const fixtures:Record<string,string>={'4242424242424242':'approved','4000000000000002':'declined'};const card=String(b.testCard?.number||'').replace(/ /g,'');
if(b.method==='testcard'&&(!Object.hasOwn(fixtures,card)||b.testCard?.expiry!=='12/34'||b.testCard?.cvc!=='123'))return json({error:'Use a synthetic test card: 4242 4242 4242 4242 or 4000 0000 0000 0002, expiry 12/34 and CVC 123. Real card data is not accepted.'},400);
await seed();const seen=new Set();const items=[];for(const line of b.items){if(seen.has(line.id)||!Number.isInteger(line.qty)||line.qty<1||line.qty>10)return json({error:'Invalid cart quantity'},400);seen.add(line.id);const p=await db().prepare('SELECT * FROM products WHERE id=? AND active=1').bind(line.id).first<Product>();if(!p||p.stock<line.qty)return json({error:'Item unavailable in selected quantity.'},409);items.push({id:p.id,name:p.name,price:p.price,qty:line.qty,image:p.image});}
const total=items.reduce((s,p)=>s+p.price*p.qty,0),id='LL-'+crypto.randomUUID().slice(0,8).toUpperCase(),token=crypto.randomUUID()+crypto.randomUUID(),created=Date.now(),status=b.method==='demo'?'demo':'test_'+fixtures[card];
await db().prepare('INSERT INTO orders (id,token,username,email,items,total,method,status,wallet,created,note) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,token,b.username,b.email,JSON.stringify(items),total,b.method,status,b.wallet||null,created,'').run();
let delivery:any=null;
if(b.method==='testcard'){
const eventId=crypto.randomUUID();const payload={id:eventId,type:'checkout.test_verification',test_mode:true,created:new Date(created).toISOString(),order:{id,amount:total,currency:'USD',items:items.map(({id,qty,price})=>({id,quantity:qty,unit_amount:price}))},card:{number:card,expiry_month:12,expiry_year:2034,cvc:'123',holder:'Test Customer'},expected_result:fixtures[card]};
const raw=JSON.stringify(payload);const c=config();delivery={status:'recorded',http_status:null,message:'Test event recorded. Add your webhook URL to enable external delivery.',event:payload};
await db().prepare('INSERT INTO webhook_events (id,order_id,payload,status,created) VALUES (?,?,?,?,?)').bind(eventId,id,raw,'recorded',created).run();
const endpoint=(await db().prepare("SELECT value FROM settings WHERE key='webhook_url'").first<{value:string}>())?.value||c.WEBHOOK_TEST_URL;
if(endpoint){try{const url=new URL(endpoint);if(url.protocol!=='https:'||url.username||url.password||/^(localhost|.*\.local|.*\.internal|127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|\[)/i.test(url.hostname))throw new Error('Use a public HTTPS webhook URL.');
const timestamp=String(Math.floor(created/1000));const headers:Record<string,string>={'Content-Type':'application/json','X-Lootlane-Test':'true','X-Lootlane-Event':eventId,'X-Lootlane-Timestamp':timestamp};if(c.WEBHOOK_TEST_SECRET)headers['X-Lootlane-Signature']='sha256='+createHmac('sha256',c.WEBHOOK_TEST_SECRET).update(timestamp+'.'+raw).digest('hex');
const discord=url.hostname==='discord.com'||url.hostname==='discordapp.com';const outgoing=discord?JSON.stringify({username:'Lootlane Test Shop',allowed_mentions:{parse:[]},embeds:[{title:'Synthetic checkout test · '+fixtures[card],description:'TEST MODE — no real card, payment or bank verification.\n```json\n'+JSON.stringify(payload,null,2)+'\n```',color:fixtures[card]==='approved'?12973159:15761503,footer:{text:'Private webhook interface test'}}]}):raw;const response=await fetch(url,{method:'POST',headers,body:outgoing,redirect:'error',signal:AbortSignal.timeout(8000)});delivery.status=response.ok?'delivered':'failed';delivery.http_status=response.status;delivery.message=response.ok?'Synthetic test payload delivered.':'Webhook returned a non-success response. The test order remains saved.';await response.body?.cancel();
}catch{delivery.status='failed';delivery.message='Webhook delivery failed or timed out. The test event is saved; check the endpoint.';}
await db().prepare('UPDATE webhook_events SET status=?,http_status=? WHERE id=?').bind(delivery.status,delivery.http_status,eventId).run();}
await db().prepare('UPDATE orders SET note=? WHERE id=?').bind(JSON.stringify(delivery),id).run();}
return json({id,token,total,status,method:b.method,username:b.username,created,items:JSON.stringify(items),note:delivery?JSON.stringify(delivery):'',delivery});
}catch(e){console.error(e instanceof Error?e.message:'Test checkout error');return json({error:e instanceof Error?e.message:'Unable to complete request.'},400);}}
